name: Add text file with random byte data
on:
  schedule:
    - cron: '4/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Create the random data
        run: python3 write_data.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Generate random byte data'
